[package]
name = "palimpsest-processor"
version = "0.1.0"
authors = ["Ryan1729 <Ryan1729@gmail.com>"]

[workspace]

[dependencies]
bear-lib-terminal = "1.3.2"
bear-lib-terminal-sys = "1.1.1"
libloading = "0.3"

[dependencies.game]
path = "./game"

[dependencies.common]
path = "./common"
